export const TODO_ACTION_TYPES = {
   ADD_TODO : 'ADD_TODO',
   REMOVE_TODO : 'REMOVE_TODO',
   EDIT_TODO : 'EDIT_TODO'
}

export const FETCH_WEATHER_DATA_REQUEST = "FETCH_WEATHER_DATA_REQUEST";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_FAILURE = "FETCH_WEATHER_DATA_FAILURE";